services:
  app:
    build: .
    image: app
    container_name: app
    volumes:
      - static:/usr/src/app/.static
    command: /usr/src/app/entrypoint.sh
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}
      - SECRET_KEY=${SECRET_KEY}
    restart: always

  db:
    image: postgres
    container_name: db
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data

  nginx:
    build: ./docker/nginx
    image: nginx
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - static:/www/static/

volumes:
  db:
      name: db
  static:
      name: static
